### ISSUE TITLE
No Custom Progress 

### ISSUE THREAD

**Issue by appsapiconsole** [Shahidzbi4213/SampleReelsApp#4]
I think the progress library is showing before playing video must be given by developer using this library,
Also you can show default progress bar if not given

**Comment by Shahidzbi4213** [comment]
You can pass a custom loader like that the option is already given  ` ReelsPlayer(
        modifier = modifier.fillMaxSize(),
        videoList = videosList.map { VideoSource.UrlResource(it) },
        indexOfVideo = index,
        reelConfig = ReelsConfig(
            playerResizeMode = PlayerResizeMode.FILL,
            videoScalingMode = VideoScalingMode.FIT_WITH_CROPPING,
            repeatMode = RepeatMode.ALL,
            thumbnailDisplayMode = ThumbnailDisplayMode.FILL,
            enableCache = false,
            playerSize = Size(MATCH_PARENT, MATCH_PARENT),
            playerLoader = { VideoLoader(Modifier) }
        )
    ) { page ->
    }`

Here is the  Custom Loader Compasable `@Composable
fun VideoLoader(modifier: Modifier = Modifier) {

    val composition by rememberLottieComposition(spec = LottieCompositionSpec.RawRes(R.raw.video_loading))
    Box(modifier = Modifier.fillMaxSize(),
        contentAlignment = Alignment.Center) {
        LottieAnimation(
            composition = composition,
            iterations = LottieConstants.IterateForever,
            modifier = modifier
                .size(50.dp)
                .align(Alignment.Center)
        )
    }
}`
